# k8s-cluster.yml
kube_version: v1.26.5
kubeconfig_localhost: true

kubelet_image_gc_high_threshold: 75
kubelet_image_gc_low_threshold: 70

## cri
container_manager: containerd

## cni
kube_network_plugin: cilium
### cilium
# https://github.com/kubernetes-sigs/kubespray/blob/c6814354325947c9ee99e326d15afcd14aad8eb9/docs/cilium.md#install-cilium-hubble
# https://github.com/kubernetes-sigs/kubespray/blob/master/roles/network_plugin/cilium/defaults/main.yml
cilium_version: "v1.13.4"
# use cilium kube-proxy
# https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubeproxy-free
# Should disable kube-proxy at kubespray
# https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md
cilium_kube_proxy_replacement: strict

cilium_enable_hubble: true
cilium_hubble_install: true
cilium_hubble_tls_generate: true
cilium_config_extra_vars:
  # BGP ControlPlane
  # https://docs.cilium.io/en/latest/network/bgp-control-plane/
  # Bug: https://github.com/cilium/cilium/issues/24663
  enable-bgp-control-plane: true
# https://docs.cilium.io/en/v1.13/cmdref/cilium-agent/
cilium_agent_custom_args:
  # BGP ControlPlane
  # https://docs.cilium.io/en/latest/network/bgp-control-plane/
  # Bug: https://github.com/cilium/cilium/issues/24663
  - "--enable-bgp-control-plane=true"
